CREATE OR REPLACE TRIGGER TRG_AFTER_LOGON AFTER LOGON ON SCHEMA -- Trigger sets NLS for all connections
BEGIN

	EXECUTE IMMEDIATE '
		ALTER SESSION SET 
			NLS_CALENDAR = ''GREGORIAN''
			NLS_COMP = ''BINARY''
			NLS_CURRENCY = ''USD''
			NLS_DATE_FORMAT = ''RRRR.MM.DD''
			NLS_DATE_LANGUAGE = ''AMERICAN''
			NLS_DUAL_CURRENCY = ''$''
			NLS_ISO_CURRENCY = ''AMERICA''
			NLS_LANGUAGE = ''AMERICAN''
			NLS_LENGTH_SEMANTICS = ''BYTE''
			NLS_NCHAR_CONV_EXCP = ''FALSE''
			NLS_NUMERIC_CHARACTERS = ''.,''
			NLS_SORT = ''BINARY''
			NLS_TERRITORY = ''AMERICA''
			NLS_TIME_FORMAT = ''HH24:MI:SSXFF''
			NLS_TIMESTAMP_FORMAT = ''RRRR.MM.DD HH24:MI:SSXFF''
			NLS_TIMESTAMP_TZ_FORMAT = ''RRRR.MM.DD HH24:MI:SSXFF TZM''
			NLS_TIME_TZ_FORMAT = ''HH24:MI:SSXFF TZM''
	';
	EXECUTE IMMEDIATE 'COMMIT';
	
END;
/
