CREATE OR REPLACE TRIGGER TRG_AFTER_LOGON AFTER LOGON ON SCHEMA
BEGIN
    EXECUTE IMMEDIATE '
        ALTER SESSION SET 
            NLS_CALENDAR = ''GREGORIAN''
            NLS_COMP = ''BINARY''
            NLS_CURRENCY = ''£''
            NLS_DATE_FORMAT = ''DD-MON-RRRR''
            NLS_DATE_LANGUAGE = ''ENGLISH''
            NLS_DUAL_CURRENCY = ''£''
            NLS_ISO_CURRENCY = ''UNITED KINGDOM''
            NLS_LANGUAGE = ''ENGLISH''
            NLS_LENGTH_SEMANTICS = ''BYTE''
            NLS_NCHAR_CONV_EXCP = ''FALSE''
            NLS_NUMERIC_CHARACTERS = ''.,''
            NLS_SORT = ''BINARY''
            NLS_TERRITORY = ''UNITED KINGDOM''
            NLS_TIME_FORMAT = ''HH24:MI:SSXFF''
            NLS_TIMESTAMP_FORMAT = ''DD-MON-RRRR HH24:MI:SSXFF''
            NLS_TIMESTAMP_TZ_FORMAT = ''DD-MON-RRRR HH24:MI:SSXFF TZR''
            NLS_TIME_TZ_FORMAT = ''HH24:MI:SSXFF TZR''
    ';
    EXECUTE IMMEDIATE 'COMMIT';
END;
/
