CREATE OR REPLACE TRIGGER TRG_AFTER_LOGON AFTER LOGON ON SCHEMA
BEGIN
    EXECUTE IMMEDIATE '
        ALTER SESSION SET 
            NLS_CALENDAR = ''GREGORIAN''
            NLS_COMP = ''BINARY''
            NLS_CURRENCY = ''$''
            NLS_DATE_FORMAT = ''MM/DD/YYYY''
            NLS_DATE_LANGUAGE = ''AMERICAN''
            NLS_DUAL_CURRENCY = ''$''
            NLS_ISO_CURRENCY = ''AMERICA''
            NLS_LANGUAGE = ''AMERICAN''
            NLS_LENGTH_SEMANTICS = ''BYTE''
            NLS_NCHAR_CONV_EXCP = ''FALSE''
            NLS_NUMERIC_CHARACTERS = ''.,''
            NLS_SORT = ''BINARY''
            NLS_TERRITORY = ''AMERICA''
            NLS_TIME_FORMAT = ''HH24:MI:SSXFF''
            NLS_TIMESTAMP_FORMAT = ''MM/DD/YYYY HH24:MI:SSXFF''
            NLS_TIMESTAMP_TZ_FORMAT = ''MM/DD/YYYY HH24:MI:SSXFF TZH:TZM''
            NLS_TIME_TZ_FORMAT = ''HH24:MI:SSXFF TZH:TZM''
    ';
    EXECUTE IMMEDIATE 'COMMIT';
END;
/
